# Google Cloud Build configuration for automated deployment
# Builds and deploys:
# 1) thanksgiving-app (React/Vite → NGINX)

steps:
  # ==========================
  # BUILD MAIN APP
  # ==========================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-main-app'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push main app
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-main-app'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # ==========================
  # DEPLOY MAIN APP
  # ==========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-main-app'
    entrypoint: gcloud
    args:
      [
        'run','deploy','${_SERVICE_NAME}',
        '--image','gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '--platform','managed',
        '--region','${_REGION}',
        '--allow-unauthenticated',
        '--memory','512Mi',
        '--cpu','1',
        '--min-instances','0',
        '--max-instances','10',
        '--timeout','300',
        '--port','8080'
      ]

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
