# Google Cloud Build configuration for automated deployment
# Builds and deploys:
# 1) rsvp-proxy (Node.js → Apps Script)
# 2) thanksgiving-app (React/Vite → NGINX)

steps:
  # ==========================
  # BUILD PROXY SERVICE
  # ==========================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-proxy'
    dir: 'proxy'
    args:
      - 'build'
      - '--build-arg=APPS_SCRIPT_URL=${_APPS_SCRIPT_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_PROXY_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_PROXY_SERVICE_NAME}:latest'
      - '.'

  # Push proxy image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-proxy'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_PROXY_SERVICE_NAME}:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_PROXY_SERVICE_NAME}:latest'

  # ==========================
  # DEPLOY PROXY SERVICE
  # ==========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-proxy'
    entrypoint: gcloud
    args:
      [
        'run','deploy','${_PROXY_SERVICE_NAME}',
        '--image','gcr.io/$PROJECT_ID/${_PROXY_SERVICE_NAME}:$SHORT_SHA',
        '--platform','managed',
        '--region','${_REGION}',
        '--allow-unauthenticated',
        '--memory','256Mi',
        '--cpu','1',
        '--min-instances','0',
        '--max-instances','10',
        '--timeout','60',
        '--port','8080',
        '--set-env-vars','APPS_SCRIPT_URL=${_APPS_SCRIPT_URL},PORT=8080'
      ]

  # ==========================
  # GET PROXY URL (WITH RETRY)
  # ==========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-proxy-url'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Waiting for proxy service URL..."
        for i in {1..10}; do
          PROXY_URL=$$(gcloud run services describe ${_PROXY_SERVICE_NAME} \
            --region=${_REGION} \
            --format='value(status.url)')
          if [[ ! -z "$$PROXY_URL" ]]; then
            echo "✓ Proxy URL: $$PROXY_URL"
            break
          fi
          echo "Proxy URL not ready yet... retrying in 5s"
          sleep 5
        done

        if [[ -z "$$PROXY_URL" ]]; then
          echo "ERROR: Proxy URL never resolved"
          exit 1
        fi

        echo "$$PROXY_URL/api/rsvp" > /workspace/proxy_api_url.txt

  # ==========================
  # BUILD MAIN APP (inject proxy URL)
  # ==========================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-main-app'
    entrypoint: bash
    args:
      - '-c'
      - |
        PROXY_API_URL=$$(cat /workspace/proxy_api_url.txt)
        echo "Using Proxy API URL: $$PROXY_API_URL"

        docker build \
          --build-arg VITE_RSVP_API_URL="$$PROXY_API_URL" \
          -t gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest \
          .

  # Push main app
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-main-app'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # ==========================
  # DEPLOY MAIN APP
  # ==========================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-main-app'
    entrypoint: gcloud
    args:
      [
        'run','deploy','${_SERVICE_NAME}',
        '--image','gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '--platform','managed',
        '--region','${_REGION}',
        '--allow-unauthenticated',
        '--memory','512Mi',
        '--cpu','1',
        '--min-instances','0',
        '--max-instances','10',
        '--timeout','300',
        '--port','8080'
      ]

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'